name: sql2sqlbench-py310
channels:
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - bzip2=1.0.8
  - ca-certificates=2025.2.25
  - ld_impl_linux-64=2.40
  - libffi=3.4.4
  - libgcc-ng=11.2.0
  - libgomp=11.2.0
  - libstdcxx-ng=11.2.0
  - libuuid=1.41.5
  - ncurses=6.4
  - openssl=3.0.16
  - pip=25.0
  - python=3.10.16
  - readline=8.2
  - setuptools=75.8.0
  - sqlite=3.45.3
  - tk=8.6.14
  - tqdm=4.67.1
  - wheel=0.45.1
  - xz=5.6.4
  - zlib=1.2.13
  - pip:
      - accelerate==1.5.2
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.11.14
      - aiosignal==1.3.2
      - alembic==1.15.1
      - aliyun-python-sdk-core==2.13.36
      - annotated-types==0.7.0
      - antlr4-python3-runtime==4.13.2
      - anyio==4.9.0
      - apscheduler==3.11.0
      - asgiref==3.8.1
      - async-timeout==4.0.3
      - attrs==25.3.0
      - backoff==2.2.1
      - bcrypt==4.3.0
      - beautifulsoup4==4.13.4
      - build==1.2.2.post1
      - cachetools==5.5.2
      - certifi==2025.4.26
      - cffi==1.17.1
      - chardet==5.2.0
      - charset-normalizer==3.4.1
      - chroma-hnswlib==0.7.6
      - chromadb==0.6.3
      - click==8.1.8
      - coloredlogs==15.0.1
      - contourpy==1.3.2
      - cryptography==44.0.2
      - cycler==0.12.1
      - dataclasses-json==0.6.7
      - deprecated==1.2.18
      - distro==1.9.0
      - durationpy==0.9
      - exceptiongroup==1.2.2
      - faker==37.3.0
      - fastapi==0.115.12
      - filelock==3.18.0
      - flask==2.2.5
      - flask-apscheduler==1.12.3
      - flask-caching==1.10.1
      - flask-cors==3.0.10
      - flask-migrate==3.1.0
      - flask-sqlalchemy==3.0.2
      - flatbuffers==25.2.10
      - fonttools==4.59.0
      - frozenlist==1.5.0
      - fsspec==2025.3.0
      - func-timeout==4.3.5
      - google-auth==2.38.0
      - googleapis-common-protos==1.69.2
      - greenlet==3.1.1
      - grpcio==1.71.0
      - h11==0.14.0
      - httpcore==1.0.7
      - httptools==0.6.4
      - httpx==0.28.1
      - httpx-sse==0.4.0
      - huggingface-hub==0.29.3
      - humanfriendly==10.0
      - idna==3.10
      - importlib-metadata==8.6.1
      - importlib-resources==6.5.2
      - isodate==0.7.2
      - itsdangerous==2.2.0
      - jinja2==3.1.6
      - jiter==0.9.0
      - jmespath==0.10.0
      - joblib==1.4.2
      - jsonpatch==1.33
      - jsonpointer==3.0.0
      - kiwisolver==1.4.8
      - kubernetes==32.0.1
      - langchain==0.3.21
      - langchain-community==0.3.20
      - langchain-core==0.3.49
      - langchain-openai==0.3.11
      - langchain-text-splitters==0.3.7
      - langsmith==0.3.19
      - lxml==5.3.2
      - mako==1.3.9
      - markdown-it-py==3.0.0
      - markupsafe==3.0.2
      - marshmallow==3.26.1
      - matplotlib==3.10.3
      - mdurl==0.1.2
      - mmh3==5.1.0
      - monotonic==1.6
      - mpmath==1.3.0
      - multidict==6.2.0
      - mypy-extensions==1.0.0
      - mysql-connector-python==9.3.0
      - networkx==3.4.2
      - numpy==2.2.4
      - nvidia-cublas-cu12==12.4.5.8
      - nvidia-cuda-cupti-cu12==12.4.127
      - nvidia-cuda-nvrtc-cu12==12.4.127
      - nvidia-cuda-runtime-cu12==12.4.127
      - nvidia-cudnn-cu12==9.1.0.70
      - nvidia-cufft-cu12==11.2.1.3
      - nvidia-curand-cu12==10.3.5.147
      - nvidia-cusolver-cu12==11.6.1.9
      - nvidia-cusparse-cu12==12.3.1.170
      - nvidia-cusparselt-cu12==0.6.2
      - nvidia-nccl-cu12==2.21.5
      - nvidia-nvjitlink-cu12==12.4.127
      - nvidia-nvtx-cu12==12.4.127
      - oauthlib==3.2.2
      - onnxruntime==1.21.0
      - openai==1.69.0
      - opentelemetry-api==1.31.1
      - opentelemetry-exporter-otlp-proto-common==1.31.1
      - opentelemetry-exporter-otlp-proto-grpc==1.31.1
      - opentelemetry-instrumentation==0.52b1
      - opentelemetry-instrumentation-asgi==0.52b1
      - opentelemetry-instrumentation-fastapi==0.52b1
      - opentelemetry-proto==1.31.1
      - opentelemetry-sdk==1.31.1
      - opentelemetry-semantic-conventions==0.52b1
      - opentelemetry-util-http==0.52b1
      - oracledb==3.0.0
      - orjson==3.10.16
      - outcome==1.3.0.post0
      - overrides==7.7.0
      - packaging==24.2
      - pandas==2.2.3
      - paramiko==3.5.1
      - pillow==11.1.0
      - posthog==3.23.0
      - propcache==0.3.1
      - protobuf==5.29.4
      - psutil==7.0.0
      - psycopg==3.2.9
      - psycopg-binary==3.2.9
      - psycopg2==2.9.10
      - psycopg2-binary==2.9.10
      - pyasn1==0.6.1
      - pyasn1-modules==0.4.2
      - pycparser==2.22
      - pydantic==2.11.0
      - pydantic-core==2.33.0
      - pydantic-settings==2.8.1
      - pygments==2.19.1
      - pyjwt==2.3.0
      - pymysql==1.0.2
      - pynacl==1.5.0
      - pyparsing==3.2.3
      - pypika==0.48.9
      - pyproject-hooks==1.2.0
      - pysocks==1.7.1
      - python-dateutil==2.9.0.post0
      - python-dotenv==1.1.0
      - pytz==2025.2
      - pyyaml==6.0
      - readerwriterlock==1.0.9
      - regex==2024.11.6
      - requests==2.32.3
      - requests-oauthlib==2.0.0
      - requests-toolbelt==1.0.0
      - rich==13.9.4
      - rsa==4.9
      - safetensors==0.5.3
      - scikit-learn==1.6.1
      - scipy==1.15.2
      - selenium==4.33.0
      - sentence-transformers==4.0.1
      - shellingham==1.5.4
      - six==1.17.0
      - sniffio==1.3.1
      - sortedcontainers==2.4.0
      - soupsieve==2.6
      - sqlalchemy==2.0.40
      - sqlglot==26.6.0
      - sqlparse==0.5.3
      - starlette==0.46.1
      - sympy==1.13.1
      - tenacity==9.0.0
      - threadpoolctl==3.6.0
      - tiktoken==0.9.0
      - tokenizers==0.21.1
      - tomli==2.2.1
      - torch==2.6.0
      - transformers==4.50.2
      - trio==0.30.0
      - trio-websocket==0.12.2
      - triton==3.2.0
      - typer==0.15.2
      - typing-extensions==4.13.2
      - typing-inspect==0.9.0
      - typing-inspection==0.4.0
      - tzdata==2025.2
      - tzlocal==5.3.1
      - urllib3==2.4.0
      - uvicorn==0.34.0
      - uvloop==0.21.0
      - watchfiles==1.0.4
      - websocket-client==1.8.0
      - websockets==15.0.1
      - werkzeug==3.1.3
      - wrapt==1.17.2
      - wsproto==1.2.0
      - yarl==1.18.3
      - zipp==3.21.0
      - zstandard==0.23.0
