# Knowledge base initialization configuration file, used to initialize knowledge bases and embedding models.
# This file is only used during initialization. Subsequent modifications can be made directly in the database.

# LLM model configuration
LLM_MODELS:
  - name: "moonshot-v1-128k"                          # Model name
    deployment_type: "cloud"                # Deployment type: cloud or local
    category: "llm"                         # Model category
    api_base: "https://api.moonshot.cn/v1"   # API base URL
    api_key: "sk-2oRF6NE4FlbpzrCdEjEE98fOrntvozQbHM1O5BNCQvDOuTbY"          # Replace with your actual API key
    path: "./local_models/gpt-4o"           # Local model path. Please replace with the actual path of the local model.
    description: "OpenAI LLM模型，用于生成文本"  # Model description
    temperature: 1                        # Temperature for text generation
#    max_tokens: 128000                      # Maximum tokens for generation


# Embedding model configuration
EMBEDDING_MODELS:
  - name: "all-MiniLM-L6-v2"          # Model name
    deployment_type: "local"                # Deployment type: cloud or local
    category: "embedding"                   # Model category
    api_base: "https://api.openai.com/v1"   # API base URL
    api_key: "your-openai-api-key"          # Replace with your actual API key
    path: "/home/gyy/cracksql_test/all-MiniLM-L6-v2"  # Local model path. Please replace with the actual path of the local model.
    dimension: 1536                         # Vector dimension
    description: "CrackSQL all-MiniLM-L6-v2"  # Model description

# Knowledge base configuration
KNOWLEDGE_BASES:
  - kb_name: "mysql_knowledge"              # Knowledge base name
    db_type: "mysql"                        # Database type
    kb_info: "MySQL数据库知识库，包含MySQL的关键字、函数、操作符等信息"  # Knowledge base description
    embedding_model: "all-MiniLM-L6-v2"  # Embedding model to use
    knowledge_files: # Knowledge files to import
      - "/home/gyy/cracksql_test/mysql_8_kb.json"  # Knowledge file path

  # PostgreSQL knowledge base  
  - kb_name: "postgresql_knowledge"         # Knowledge base name
    db_type: "postgresql"                   # Database type
    kb_info: "PostgreSQL数据库知识库，包含PostgreSQL的关键字、函数、操作符等信息"  # Knowledge base description
    embedding_model: "all-MiniLM-L6-v2"  # Embedding model to use
    knowledge_files: # Knowledge files to import
      - "/home/gyy/cracksql_test/pg_14_kb.json"

  # Oracle knowledge base
  - kb_name: "oracle_knowledge"             # Knowledge base name
    db_type: "oracle"                       # Database type
    kb_info: "Oracle 数据库知识库，包含Oracle的关键字、函数、操作符等信息"  # Knowledge base description
    embedding_model: "all-MiniLM-L6-v2"  # Embedding model to use
    knowledge_files: # Knowledge files to import
      - "/home/gyy/cracksql_test/oracle_11_kb.json"